// <auto-generated />
using System;
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240115141805_NewTableCo")]
    partial class NewTableCo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EntityLayer.Concrete.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Banner")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FacebookAdress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InstagramAdress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("icon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AdminID");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CategoryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CategoryIcon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("CategoryStatus")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("CategoryID");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Contact", b =>
                {
                    b.Property<int>("ContactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ContactDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContactMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("ContactStatus")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ContactSubject")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ContactID");

                    b.ToTable("contacts");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Dava", b =>
                {
                    b.Property<int>("DavaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DavaDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DavaDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DavaIcon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DavaName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("DavaStatus")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("DavaID");

                    b.ToTable("davas");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Makale", b =>
                {
                    b.Property<int>("MakaleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("MakaleContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("MakaleCreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MakaleImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("MakaleStatus")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MakaleTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MakaleID");

                    b.HasIndex("CategoryID");

                    b.ToTable("makales");
                });

            modelBuilder.Entity("EntityLayer.Concrete.SubScribe", b =>
                {
                    b.Property<int>("SubID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("SubDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SubEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("SubStatus")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("SubID");

                    b.ToTable("subScribes");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Makale", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Category", "category")
                        .WithMany("makales")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Category", b =>
                {
                    b.Navigation("makales");
                });
#pragma warning restore 612, 618
        }
    }
}
